server:
  port: ${PORT:8082}

spring:
  application:
    name: movie-service
  
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/cineverse}
    
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.cineverse: INFO
